### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by JohnWE**
Need to update this version number to let Composer grab the 1.2 release.

### CODE REVIEW

**Comment by JohnWE** [comment]
Require dev-master gets the latest changes, but a different require like Require ^1.1 doesn't get v1.2.

**Comment by greatislander** [comment]
@JohnWE @kesar If you omit the version from composer.json, Packagist will just pick up versions from your tags.

**Comment by JohnWE** [comment]
That sounds like an even better solution.

**Comment by j0k3r** [comment]
So you should update your PR and remove the version line.
@kesar any news about merging that to publish the last 1.2 version on packagist?

**Comment by JohnWE** [comment]
All done.

**Comment by j0k3r** [comment]
@kesar are you ok with that PR? It blocks the version 1.2 to be published on packagist :disappointed_relieved:

**Pull request merged**
