### PR TITLE
Update to htmLawed v1.2

### PR DESCRIPTION
**Pull request by greatislander**
[htmLawed v1.2](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/index.php) was released on February 11 with support for HTML5 elements. This PR updates htmLawed to v1.2.

### CODE REVIEW

**Comment by greatislander** [comment]
Thanks @kesar! Can you tag a new release for Packagist? 👍

**Comment by kesar** [comment]
done 👍 https://github.com/kesar/HTMLawed/tree/1.2

Thanks!

**Comment by greatislander** [comment]
Cheers! It isn't showing up on Packagist.org yet for some reason…

**Comment by kesar** [comment]
I guess it takes some time to update, because in the releases appears -> https://github.com/kesar/HTMLawed/releases

**Comment by mlocati** [comment]
Packagist is updated with a delay that's usually up to a few minutes: this is taking quite too much. At https://packagist.org/packages/htmlawed/htmlawed there's still 1.1.22

@kesar You should try to manually update the packagist page, and/or be sure that Packagist is listed in the services at https://github.com/kesar/HTMLawed/settings/installations

**Comment by greatislander** [comment]
@kesar Any updates on this?

**Comment by j0k3r** [comment]
@kesar does your Github token is still up to date on Packagist? Does the repo is auto-updated?
Maybe you have to re-enable the autoupdate. 
And in the mean time, you might update it manually.

**Comment by greatislander** [comment]
@kesar There's still no tag on Packagist. Can you manually update it?

**Pull request merged**
